export const AI_FEATURES = [
  {
    title: 'GPT API Integration',
    description: 'Seamless OpenAI integration for intelligent conversational experiences.',
    icon: '🧠',
  },
  {
    title: 'Smart Automation',
    description: 'Workflow automation with AI-driven task scheduling and decision support.',
    icon: '⚡',
  },
  {
    title: 'AI Chatbot Systems',
    description: 'Context-aware chatbots with memory, streaming, and custom knowledge bases.',
    icon: '💬',
  },
  {
    title: 'AI Fitness Plans',
    description: 'Personalized workout and nutrition plans generated by machine learning.',
    icon: '🏋️',
  },
  {
    title: 'AI Study Systems',
    description: 'Adaptive learning paths, flashcards, and intelligent study scheduling.',
    icon: '📚',
  },
  {
    title: 'Semantic Search',
    description: 'Vector embeddings and NLP for intelligent content discovery.',
    icon: '🔍',
  },
] as const
